//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thetaskmanager
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskGroup
    {
        public TaskGroup()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public byte id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public byte userID { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
