//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thetaskmanager
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.TaskGroups = new HashSet<TaskGroup>();
            this.Tasks = new HashSet<Task>();
            this.TaskTypes = new HashSet<TaskType>();
        }
    
        public byte id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
    
        public virtual ICollection<TaskGroup> TaskGroups { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<TaskType> TaskTypes { get; set; }
    }
}
